[package]
edition = "2021"
name = "basic_video_player"
version = "0.1.0"

[dependencies]
video_player = {path = "../../", package = "iced_pure_video_player"}

[dependencies.iced]
features = ["tokio", "debug", "image", "svg", "canvas"]
version = "0.6"
